name: Run video.py

on:
  workflow_dispatch:
  push:
    paths:
      - video.py
      - .github/workflows/video.yml

jobs:
  run-video:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai

      - name: Run video.py
        run: python video.py
